export enum UserActionTypes {
    SET_AUTH_STATE = 'SET_AUTH_STATE',
    SIGN_IN_USER = 'SIGN_IN_USER',
    SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR = 'SIGN_UP_ERROR',
    LOG_OUT = 'LOG_OUT',
    FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
    FETCH_USER_ERROR = 'FETCH_USER_ERROR'
}